name: build-ami
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-ami:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`

      - name: Zip the repo code
        run: zip -r webapp.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/packer.pkr.hcl"

      - name: Build AMI with Packer
        run: |
          packer build \
          -var "region=${{ vars.REGION }}" \
          -var "ssh_user=${{ vars.SSH_USER }}" \
          -var "HOST=${{ vars.HOST }}" \
          -var "USERNAME=${{ secrets.USERNAME }}" \
          -var "PASSWORD=${{ secrets.PASSWORD }}" \
          -var "DB_NAME=${{ vars.DB_NAME }}" \
          -var "DIALECT=${{ vars.DIALECT }}" \
          -var "PORT=${{ vars.PORT }}" \
          -var "NODE_ENV=${{ vars.NODE_ENV }}" \
          -var "account_to_share=${{ vars.ACCOUNT_TO_SHARE }}" \
          -var "instance_type=${{ vars.INSTANCE_TYPE }}" \
          -var "profile=${{ vars.PROFILE }}" \
          ./packer/packer.pkr.hcl

      - name: Update Launch Template
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.REGION }}
        env:
          AWS_ACCESS_KEY_ID_DEV: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_ACCESS_KEY_ID_DEMO: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
          AWS_SECRET_ACCESS_KEY_DEMO: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
          run: |
            export AWS_ACCESS_KEY_ID_DEV=$AWS_ACCESS_KEY_ID_DEV
            export AWS_SECRET_ACCESS_KEY_DEV=$AWS_SECRET_ACCESS_KEY_DEV
            export AWS_ACCESS_KEY_ID_DEMO=$AWS_ACCESS_KEY_ID_DEMO
            export AWS_SECRET_ACCESS_KEY_DEMO=$AWS_SECRET_ACCESS_KEY_DEMO
            chmod +x attach_latest_ami.sh 
            ./attach_latest_ami.sh
