name: webapp-github-action
on:
  workflow_dispatch:
    pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node --version
      - run: npm --version 

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`

      - name : Zip the repo code
        run: zip -r webapp.zip .

      - run: npm install
      - run: npm test

      - name: Current Location
        run: pwd

      - name: Current Location Files
        run: ls

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/packer.pkr.hcl"

      # - name: Output Vars
      #   run: |
      #     echo "USERNAME: ${{ secrets.USERNAME }}"
      #     echo "PORT: ${{ vars.PORT }}"
      #     echo "HOST: ${{ vars.HOST }}"
      
      - name: Run packer validate
        id: validate
        run: "packer validate ./packer/packer.pkr.hcl"


      
